retry the snap installation for 30 minutes
There are so many failures due to the snapd + snap store.

error: cannot install "openstack": Post
       "https://api.snapcraft.io/v2/snaps/refresh": context canceled
Command exited with non-zero status 1