latest/edge of microovn depends on core24
$ sudo snap install microovn --channel latest/edge
error: cannot perform the following tasks:
- Ensure prerequisites for "microovn" are available (cannot install snap
base "core24": no snap revision available as specified)